// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package watsonservices.actions;

import java.io.File;
import java.io.InputStream;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;

import com.ibm.watson.developer_cloud.alchemy.v1.model.ImageKeywords;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

public class CallAlchemyVisionTags extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private String apiKey;
	private IMendixObject __image;
	private system.proxies.Image image;

	public CallAlchemyVisionTags(IContext context, String apiKey, IMendixObject image)
	{
		super(context);
		this.apiKey = apiKey;
		this.__image = image;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.image = __image == null ? null : system.proxies.Image.initialize(getContext(), __image);

		// BEGIN USER CODE
		com.ibm.watson.developer_cloud.alchemy.v1.AlchemyVision service = new com.ibm.watson.developer_cloud.alchemy.v1.AlchemyVision();
		service.setApiKey(apiKey);
		
		File tempFile = new File(Core.getConfiguration().getTempPath() + "CallAlchemyVision");
		InputStream stream = Core.getFileDocumentContent(getContext(), __image);
		Files.copy(stream, tempFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
		stream.close();
		
		ImageKeywords keywords = service.getImageKeywords(tempFile, true, true).execute();
		
		java.util.List<IMendixObject> results = new java.util.ArrayList<IMendixObject>();
		
		for (com.ibm.watson.developer_cloud.alchemy.v1.model.ImageKeyword keyword : keywords.getImageKeywords()) {
			IMendixObject result = Core.instantiate(getContext(), watsonservices.proxies.Tag.entityName);
			
			result.setValue(getContext(), "Text", keyword.getText());
			result.setValue(getContext(), "Score", new BigDecimal(keyword.getScore()));
			
			results.add(result);
		}
		
		return results;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "CallAlchemyVisionTags";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
