// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package watsonservices.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import watsonservices.utils.DialogService;

public class Converse extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __conversation;
	private watsonservices.proxies.Conversation conversation;
	private String username;
	private String password;
	private String message;

	public Converse(IContext context, IMendixObject conversation, String username, String password, String message)
	{
		super(context);
		this.__conversation = conversation;
		this.username = username;
		this.password = password;
		this.message = message;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.conversation = __conversation == null ? null : watsonservices.proxies.Conversation.initialize(getContext(), __conversation);

		// BEGIN USER CODE
		return  DialogService.converse(getContext(), message, conversation, username, password);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "Converse";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
