// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package watsonservices.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import watsonservices.utils.VisualRecognitionService;

public class CreateClassifier extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __classifier;
	private watsonservices.proxies.Classifier classifier;
	private java.lang.String apikey;
	private java.lang.String url;

	public CreateClassifier(IContext context, IMendixObject classifier, java.lang.String apikey, java.lang.String url)
	{
		super(context);
		this.__classifier = classifier;
		this.apikey = apikey;
		this.url = url;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		this.classifier = __classifier == null ? null : watsonservices.proxies.Classifier.initialize(getContext(), __classifier);

		// BEGIN USER CODE
		return VisualRecognitionService.createClassifier(getContext(), classifier, apikey, url);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "CreateClassifier";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
