// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package watsonservices.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import watsonservices.utils.AssistantService;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Creates a new chat session with the IBM Assistant.
 */
public class CreateSession extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __assistant;
	private watsonservices.proxies.Assistant assistant;
	private java.lang.String apikey;
	private java.lang.String url;

	public CreateSession(IContext context, IMendixObject assistant, java.lang.String apikey, java.lang.String url)
	{
		super(context);
		this.__assistant = assistant;
		this.apikey = apikey;
		this.url = url;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.assistant = __assistant == null ? null : watsonservices.proxies.Assistant.initialize(getContext(), __assistant);

		// BEGIN USER CODE
		return AssistantService.createSession(getContext(), assistant, apikey, url);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "CreateSession";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
