// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package watsonservices.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import watsonservices.utils.VisualRecognitionService;

public class DetectFaces extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String apikey;
	private java.lang.String url;
	private IMendixObject __image;
	private system.proxies.Image image;

	public DetectFaces(IContext context, java.lang.String apikey, java.lang.String url, IMendixObject image)
	{
		super(context);
		this.apikey = apikey;
		this.url = url;
		this.__image = image;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.image = __image == null ? null : system.proxies.Image.initialize(getContext(), __image);

		// BEGIN USER CODE
		return VisualRecognitionService.detectFaces(getContext(), apikey, url, image);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "DetectFaces";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
