// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package watsonservices.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import watsonservices.utils.AlchemyLanguageService;

public class GetKeywords extends CustomJavaAction<IMendixObject>
{
	private java.lang.String apikey;
	private IMendixObject __request;
	private watsonservices.proxies.KeywordRequest request;

	public GetKeywords(IContext context, java.lang.String apikey, IMendixObject request)
	{
		super(context);
		this.apikey = apikey;
		this.__request = request;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.request = __request == null ? null : watsonservices.proxies.KeywordRequest.initialize(getContext(), __request);

		// BEGIN USER CODE
		return AlchemyLanguageService.getKeywords(getContext(), request, apikey);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetKeywords";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
