// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package watsonservices.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import watsonservices.utils.LanguageTranslationService;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetModels extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.util.List<IMendixObject> __languages;
	private java.util.List<watsonservices.proxies.Language> languages;
	private java.lang.String apikey;
	private java.lang.String url;

	public GetModels(IContext context, java.util.List<IMendixObject> languages, java.lang.String apikey, java.lang.String url)
	{
		super(context);
		this.__languages = languages;
		this.apikey = apikey;
		this.url = url;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.languages = new java.util.ArrayList<watsonservices.proxies.Language>();
		if (__languages != null)
			for (IMendixObject __languagesElement : __languages)
				this.languages.add(watsonservices.proxies.Language.initialize(getContext(), __languagesElement));

		// BEGIN USER CODE
		return LanguageTranslationService.getModels(getContext(), languages, apikey, url);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetModels";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
