// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package watsonservices.actions;

import java.util.Iterator;
import java.util.List;

import com.ibm.watson.developer_cloud.language_translation.v2.LanguageTranslation;
import com.ibm.watson.developer_cloud.language_translation.v2.model.IdentifiableLanguage;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

public class GetSupportLanguages extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private String username;
	private String password;

	public GetSupportLanguages(IContext context, String username, String password)
	{
		super(context);
		this.username = username;
		this.password = password;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		LanguageTranslation service = new LanguageTranslation();
	    service.setUsernameAndPassword(username, password);
	    
	    List<IMendixObject> results = new java.util.ArrayList<IMendixObject>();
	    
		List<IdentifiableLanguage> identifieableLanguages = service.getIdentifiableLanguages().execute();
		Iterator<IdentifiableLanguage> identifieableLanguagesIterator = identifieableLanguages.iterator();
		while(identifieableLanguagesIterator.hasNext()) {
			IdentifiableLanguage identifiableLanguage = identifieableLanguagesIterator.next();
			IMendixObject result = Core.instantiate(getContext(), watsonservices.proxies.Languages.entityName);			
			result.setValue(getContext(), "Name", identifiableLanguage.getName());
			result.setValue(getContext(), "Code", identifiableLanguage.getLanguage());			
			results.add(result);
		}
		return results;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "GetSupportLanguages";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
