// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package watsonservices.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import watsonservices.utils.SpeechToTextService;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class RecongnizeAudio extends CustomJavaAction<IMendixObject>
{
	private java.lang.String username;
	private java.lang.String password;
	private IMendixObject __audioFile;
	private system.proxies.FileDocument audioFile;
	private watsonservices.proxies.AudioFormats_SpeechToText audioFormat;
	private watsonservices.proxies.AudioLanguage audioLanguage;

	public RecongnizeAudio(IContext context, java.lang.String username, java.lang.String password, IMendixObject audioFile, java.lang.String audioFormat, java.lang.String audioLanguage)
	{
		super(context);
		this.username = username;
		this.password = password;
		this.__audioFile = audioFile;
		this.audioFormat = audioFormat == null ? null : watsonservices.proxies.AudioFormats_SpeechToText.valueOf(audioFormat);
		this.audioLanguage = audioLanguage == null ? null : watsonservices.proxies.AudioLanguage.valueOf(audioLanguage);
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.audioFile = __audioFile == null ? null : system.proxies.FileDocument.initialize(getContext(), __audioFile);

		// BEGIN USER CODE
		return SpeechToTextService.Transcribe(getContext(), this.audioFile, username, password, audioFormat, audioLanguage);
//		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "RecongnizeAudio";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
