// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package watsonservices.actions;

import java.io.File;
import java.io.InputStream;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.Iterator;
import java.util.List;

import com.ibm.watson.developer_cloud.visual_recognition.v2_beta.VisualRecognition;
import com.ibm.watson.developer_cloud.visual_recognition.v2_beta.model.VisualClassification;
import com.ibm.watson.developer_cloud.visual_recognition.v2_beta.model.VisualClassification.Image;
import com.ibm.watson.developer_cloud.visual_recognition.v2_beta.model.VisualClassification.Score;
import com.ibm.watson.developer_cloud.visual_recognition.v2_beta.model.VisualClassifier;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

/**
 * If Classifier is an empty string all existing classifiers will be used
 */
public class RecognizeImage extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __VisualRequestObject;
	private watsonservices.proxies.VisualRecognitionImage VisualRequestObject;
	private String apikey;
	private String classifier;

	public RecognizeImage(IContext context, IMendixObject VisualRequestObject, String apikey, String classifier)
	{
		super(context);
		this.__VisualRequestObject = VisualRequestObject;
		this.apikey = apikey;
		this.classifier = classifier;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.VisualRequestObject = __VisualRequestObject == null ? null : watsonservices.proxies.VisualRecognitionImage.initialize(getContext(), __VisualRequestObject);

		// BEGIN USER CODE
		VisualRecognition service = new VisualRecognition(VisualRecognition.VERSION_DATE_2015_12_02);
		service.setApiKey(this.apikey);
		
		system.proxies.FileDocument fileDocument = VisualRequestObject;
		File tempFile = new File(Core.getConfiguration().getTempPath() + fileDocument.getName());
		InputStream stream = Core.getFileDocumentContent(getContext(), __VisualRequestObject);
		Files.copy(stream, tempFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
		stream.close();
		
		List<Score> scores = null;
		if(classifier != null && classifier.length() > 0) {
			VisualClassifier classifier = new VisualClassifier(this.classifier);
			VisualClassification result = service.classify(tempFile, classifier).execute();
			List<Image> images = result.getImages();
			Image firstImage = images.get(0);
			scores = firstImage.getScores();
		}
		else {
			VisualClassification result = service.classify(tempFile).execute();
			List<Image> images = result.getImages();
			Image firstImage = images.get(0);
			scores = firstImage.getScores();
		}
		
		java.util.List<IMendixObject> mxresults = new java.util.ArrayList<IMendixObject>();
		
		Iterator<Score> scoreIterator = scores.iterator();
		while(scoreIterator.hasNext()) {
			Score score = scoreIterator.next();
			IMendixObject scoreObject = Core.instantiate(getContext(), "WatsonServices.Score");
			
			scoreObject.setValue(getContext(), "Name", score.getName());
			scoreObject.setValue(getContext(), "Score", new BigDecimal(score.getScore()));
			
			mxresults.add(scoreObject);
		}
	
		return mxresults;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "RecognizeImage";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
