// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package watsonservices.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import watsonservices.utils.SpeechToTextService;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class RecognizeAudio extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __audioFile;
	private system.proxies.FileDocument audioFile;
	private watsonservices.proxies.AudioFormats_SpeechToText audioFormat;
	private watsonservices.proxies.AudioLanguage audioLanguage;
	private java.lang.String apikey;
	private java.lang.String url;

	public RecognizeAudio(IContext context, IMendixObject audioFile, java.lang.String audioFormat, java.lang.String audioLanguage, java.lang.String apikey, java.lang.String url)
	{
		super(context);
		this.__audioFile = audioFile;
		this.audioFormat = audioFormat == null ? null : watsonservices.proxies.AudioFormats_SpeechToText.valueOf(audioFormat);
		this.audioLanguage = audioLanguage == null ? null : watsonservices.proxies.AudioLanguage.valueOf(audioLanguage);
		this.apikey = apikey;
		this.url = url;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.audioFile = __audioFile == null ? null : system.proxies.FileDocument.initialize(getContext(), __audioFile);

		// BEGIN USER CODE
		return SpeechToTextService.transcribe(getContext(), this.audioFile, audioFormat, audioLanguage, apikey, url);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "RecognizeAudio";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
